# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GfMarkdown < Formula
  desc "markdown documentation link validator"
  homepage "https://github.com/goblinfactory/gf-markdown"
  version "1.0.72"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/goblinfactory/gf-markdown/releases/download/v1.0.72/gf-markdown_1.0.72_Darwin_x86_64.tar.gz"
      sha256 "df69edbf3b8f6a4966f5429aedff3ae3bd98aaaacdd2205008bb1adb28451b13"

      def install
        bin.install "gf-markdown"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/goblinfactory/gf-markdown/releases/download/v1.0.72/gf-markdown_1.0.72_Darwin_arm64.tar.gz"
      sha256 "dd5f9762bbe8f5f0c5b011d6f9ec37a10355ec8271ad8e548b5093a212a36d08"

      def install
        bin.install "gf-markdown"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/goblinfactory/gf-markdown/releases/download/v1.0.72/gf-markdown_1.0.72_Linux_arm64.tar.gz"
      sha256 "505db05f5eeddf0b6b837931dd31435c571ad19155d7a0100050144e8fcdc8fa"

      def install
        bin.install "gf-markdown"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/goblinfactory/gf-markdown/releases/download/v1.0.72/gf-markdown_1.0.72_Linux_x86_64.tar.gz"
      sha256 "3e3a730750688958afc1f518505e349e6c7975df7c0f9657f9bb65be847100f4"

      def install
        bin.install "gf-markdown"
      end
    end
  end
end
